const fs = require('node:fs');
const path = require('node:path');
const {
  formatJson,
  generatedDirectory,
  inventoryPath,
  readJson,
  repositoryRoot,
  scanTokenUsage,
  tokenSourcePath,
} = require('./token-utils.js');

const check = process.argv.includes('--check');
const updateInventory = process.argv.includes('--update-inventory');
const source = readJson(tokenSourcePath);
const themes = Object.entries(source.themes);

function tokenValue(token, themeName) {
  return token.value ?? token.values?.[themeName];
}

function renderTheme(themeName, theme) {
  const declarations = source.tokens
    .map((token) => [token.name, tokenValue(token, themeName)])
    .filter(([, value]) => value !== undefined)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name, value]) => `  ${name}: ${value};`)
    .join('\n');

  return `/* This file is generated from tokens/tokens.json. Do not edit. */\n${theme.selector} {\n${declarations}\n}\n`;
}

function replacementFor(entry, canonicalNames) {
  if (canonicalNames.has(entry.name)) return `\`${entry.name}\` (canonical)`;
  if (entry.tier === 'system') return 'Supported compatibility name; canonical mapping pending';
  return 'Retain as a component override; canonical alias pending migration';
}

function renderCompatibility(inventory) {
  const canonicalNames = new Set(source.tokens.map((token) => token.name));
  const rows = inventory.tokens.map((entry) => {
    const locations = entry.locations.map((location) => `\`${location}\``).join('<br>');
    return `| \`${entry.name}\` | ${entry.tier} | ${replacementFor(entry, canonicalNames)} | ${locations} |`;
  });

  return `<!-- Generated by scripts/generate-tokens.js. Do not edit directly. -->
# Existing token compatibility inventory

This table records every concrete \`--md-*\` property present when the shared
token foundation was introduced. Existing names remain supported. A future
component migration must add a canonical alias before deprecating a legacy
name, and removal requires a major release.

| Existing property | Classification | Compatibility / migration | Current locations |
| --- | --- | --- | --- |
${rows.join('\n')}
`;
}

function writeOrCheck(file, content, failures) {
  if (check) {
    if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== content) {
      failures.push(path.relative(repositoryRoot, file));
    }
    return;
  }

  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
}

if (check && updateInventory) {
  throw new Error('Use either --check or --update-inventory, not both');
}

fs.mkdirSync(generatedDirectory, { recursive: true });

if (updateInventory) {
  const inventory = {
    generatedFrom: ['packages/**/*.{css,html,md,ts}', 'apps/**/*.{css,html,md,ts}', 'README.md'],
    tokens: scanTokenUsage(),
  };
  fs.writeFileSync(inventoryPath, formatJson(inventory));
}

if (!fs.existsSync(inventoryPath)) {
  throw new Error('Missing token inventory. Run pnpm tokens:inventory once and review the result.');
}

const inventory = readJson(inventoryPath);
const failures = [];

for (const [themeName, theme] of themes) {
  writeOrCheck(
    path.join(generatedDirectory, `${themeName}.css`),
    renderTheme(themeName, theme),
    failures
  );
}

writeOrCheck(
  path.join(repositoryRoot, 'tokens', 'TOKEN_COMPATIBILITY.md'),
  renderCompatibility(inventory),
  failures
);

if (failures.length > 0) {
  console.error(`Generated token artifacts are stale:\n${failures.map((file) => `- ${file}`).join('\n')}`);
  console.error('Run pnpm tokens:generate and commit the result.');
  process.exit(1);
}

if (!check) {
  console.log(`Generated ${themes.length} themes and the compatibility table.`);
}
